@startuml name

title Αναζητηση Περιεχομενου

actor User
participant TopBarView
participant TopBarController
participant Song
participant SongControllerAPI
participant SongService
participant SongRepository
participant Album
participant AlbumControllerAPI
participant AlbumService
participant AlbumRepository
participant Artist
participant ArtistControllerAPI
participant ArtistService
participant ArtistRepository
participant Playlist
participant PlaylistControllerAPI
participant PlaylistService
participant PlaylistRepository

activate TopBarController
TopBarController -> TopBarView : display()
activate TopBarView
User -> TopBarView : showSearch()
TopBarView -> TopBarView : showSearch()
User -> TopBarView : item to search
User -> TopBarView : search()
TopBarView -> TopBarController : search()
TopBarController -> Song : search()
activate Song
Song -> SongControllerAPI : fetchSong(searchName)
activate SongControllerAPI
SongControllerAPI -> SongService : findSongByName(searchName)
activate SongService
SongService -> SongRepository : SELECT * FROM song where song_name = searchName
activate SongRepository
SongRepository --> SongService : row Songs
deactivate SongRepository
SongService --> SongControllerAPI : List<Songs>
deactivate SongService
SongControllerAPI --> Song : List<Songs>
deactivate SongControllerAPI
Song --> TopBarController : List<Songs>
deactivate Song
TopBarController -> Album : search()
activate Album
Album -> AlbumControllerAPI : fetchAlbum(searchName)
activate AlbumControllerAPI
AlbumControllerAPI -> AlbumService : findAlbumByName(searchName)
activate AlbumService
AlbumService -> AlbumRepository : SELECT * FROM album WHERE album_name = searchName
activate AlbumRepository
AlbumRepository --> AlbumService : row Albums
deactivate AlbumRepository
AlbumService --> AlbumControllerAPI : List<Albums>
deactivate AlbumService
AlbumControllerAPI --> Album : List<Albums>
deactivate AlbumControllerAPI
Album --> TopBarController : List<Albums>
deactivate Album
TopBarController -> Artist : search()
activate Artist
Artist -> ArtistControllerAPI : fetchArtist(searchName)
activate ArtistControllerAPI
ArtistControllerAPI -> ArtistService : findArtistByName(searchName)
activate ArtistService
ArtistService -> ArtistRepository : SELECT * FROM artist WHERE artist_name = searchName
activate ArtistRepository
ArtistRepository --> ArtistService : row Artists
deactivate ArtistRepository
ArtistService --> ArtistControllerAPI : List<Artist>
deactivate ArtistService
ArtistControllerAPI --> Artist : List<Artist>
deactivate ArtistControllerAPI
Artist --> TopBarController : List<Artist>
deactivate Artist
TopBarController -> Playlist : search()
activate Playlist
Playlist -> PlaylistControllerAPI : fetchPlaylist(searchName)
activate PlaylistControllerAPI
PlaylistControllerAPI -> PlaylistService : findPlaylistByName(searchName)
activate PlaylistService
PlaylistService -> PlaylistRepository : SELECT * FROM playlist where name=searchName
activate PlaylistRepository
PlaylistRepository --> PlaylistService : List<playlist>
deactivate PlaylistRepository
PlaylistService --> PlaylistControllerAPI : List<Playlist>
deactivate PlaylistService
PlaylistControllerAPI --> Playlist : List<Playlist>
deactivate PlaylistControllerAPI
Playlist --> TopBarController : List<Playlist>
deactivate Playlist
alt Results != null
    TopBarController -> TopBarView : showResults()
else Results == null
    TopBarController -> TopBarView : showNoResultsError()
end
@enduml