@startuml name

title Κατέβασμα Τραγουδιού

actor AppUser
participant TopBarView
participant TopBarController
participant User
participant UserControllerAPI
participant UserService
participant UserRepository
participant Song
participant SongControllerAPI
participant SongService
participant SongRepository

activate TopBarController
activate TopBarView
AppUser -> TopBarView : downloadSong()
TopBarView -> TopBarController : downloadSong()
TopBarController -> User : checkPremium()
activate User
User -> UserControllerAPI : fetchUserStatus())
activate UserControllerAPI
UserControllerAPI -> UserService : checkUserStatus()
activate UserService
UserService -> UserRepository : SELECT status FROM user where user_id = curUserId
activate UserRepository
UserRepository --> UserService : return Premium Status
deactivate UserRepository
UserService --> UserControllerAPI : return Premium Status
deactivate UserService
UserControllerAPI --> User : return Premium Status
deactivate UserControllerAPI
User --> TopBarController : return Premium Status
deactivate User
alt IsPremium
    TopBarController ->> Song : downloadSong()
    activate Song
    Song -> SongControllerAPI : fetchSong()
    activate SongControllerAPI
    SongControllerAPI -> SongService : getSong()
    activate SongService
    SongService -> SongRepository : SELECT status FROM user where user_id = curUserId
    activate SongRepository
    SongRepository --> SongService : songFile
    deactivate SongRepository
    SongService --> SongControllerAPI : songFile
    deactivate SongService
    SongControllerAPI --> Song : songFile
    deactivate SongControllerAPI
    Song -> Song : saveSongLocaly()
    alt has enough space
        Song --> TopBarController : return download status
    else
        Song --> TopBarController : return insuficient space
        deactivate Song
        TopBarController -> TopBarView : showInsufficientSpaceError()
    end
    
else not IsPremium
    TopBarController -> TopBarView : displayGetPremiumScreen()
end

@enduml