@startuml name

title  Επιλογή Λίστας Αναπαραγωγής

actor User
participant HomeView
participant HomeController
participant PlaylistView
participant PlaylistController
participant Playlist
participant Song
participant SongControllerAPI
participant SongService
participant SongRepository
participant PlaylistControllerAPI
participant PlaylistService
participant PlaylistRepository
activate HomeController


HomeController -> HomeView : display()
activate HomeView
User -> HomeView : showPlaylists()
HomeView -> HomeController : showPlaylist()
deactivate HomeView
HomeController -> PlaylistController : getPlaylists()
deactivate HomeController
activate PlaylistController

PlaylistController -> Playlist : requestPlaylists()
activate Playlist
Playlist -> PlaylistControllerAPI : fetchPlaylistsById(userId)
activate PlaylistControllerAPI
PlaylistControllerAPI -> PlaylistService : findByUserId(userId)
activate PlaylistService
PlaylistService -> PlaylistRepository : SELECT * FROM playlist where id=userId
activate PlaylistRepository
PlaylistRepository --> PlaylistService : playlist rows
deactivate PlaylistRepository
PlaylistService --> PlaylistControllerAPI : List<Playlists>
deactivate PlaylistService
PlaylistControllerAPI --> Playlist : List<Playlists>
deactivate PlaylistControllerAPI
Playlist --> PlaylistController : List<Playlists>
deactivate Playlist

alt Playlists != null
    PlaylistController -> PlaylistView : showPlaylists()
    activate PlaylistView
    User -> PlaylistView : selectPlaylist()
    PlaylistView -> PlaylistController : getPlaylistSongs()
    PlaylistController -> Playlist : getPlaylistSongs()
    activate Playlist
    Playlist -> Song : getSongsByPlaylistId(playlistId)
    activate Song
    Song -> SongControllerAPI : fetchSongByPlId(plId)
    activate SongControllerAPI
    SongControllerAPI -> SongService : findByPlaylistId(plId)
    activate SongService
    SongService -> SongRepository : SELECT s.* FROM song.s join pl_song ps on s.id= ps.song_id where ps.playlistId = plId
    activate SongRepository
    SongRepository --> SongService : rows Songs
    deactivate SongRepository
    SongService --> SongControllerAPI : List<Songs>
    deactivate SongService
    SongControllerAPI --> Song : List<Songs>
    deactivate SongControllerAPI
    Song --> Playlist : List<Songs>
    deactivate Song
    Playlist --> PlaylistController : List<Songs>
    deactivate Playlist
    alt Songs =! null
        PlaylistController -> PlaylistView : showSelectedPlaylist()
    else Songs == null
        PlaylistController -> PlaylistView : showSelectedEmptyPlaylist()
        User -> PlaylistView : addSong()
    end
else Playlists == null
    PlaylistController -> PlaylistView : showPlaylistsScreen()
    User -> PlaylistView : createPlaylist()
end
@enduml