@startuml name

title Προσθήκη Τραγουδιού σε Λίστα Αναπαραγωγής

actor User 
participant "Αναζήτηση Περιεχομένου" as Search
participant "Επιλογή Λίστας Αναπαραγωγής" as PlaylistOfChoice
participant Playlist 
participant PlaylistController
participant PlaylistControllerAPI
participant PlaylistService
participant PlaylistRepository
activate Search
Search --> User : searchResults()
deactivate Search
activate PlaylistOfChoice
alt PlaylistOfChoice == Favorites
    User -> Playlist : song
    activate Playlist
    Playlist -> PlaylistController : addSongToFavorites()
    activate PlaylistController
    PlaylistController -> PlaylistControllerAPI : addSong()
    deactivate PlaylistController
    activate PlaylistControllerAPI
    PlaylistControllerAPI -> PlaylistService : addSong()
    deactivate PlaylistControllerAPI
    activate PlaylistService
    PlaylistService -> PlaylistRepository : addSong()
    deactivate PlaylistService
    activate PlaylistRepository
    alt Song exists 
        Playlist --> User : Song exists
    end
    deactivate Playlist
else
    User -> PlaylistOfChoice : song
    PlaylistOfChoice -> Playlist : song
    activate Playlist
    deactivate PlaylistOfChoice
    Playlist -> PlaylistController : addSong()
    activate PlaylistController
    PlaylistController -> PlaylistControllerAPI : addSong()
    deactivate PlaylistController
    activate PlaylistControllerAPI
    PlaylistControllerAPI -> PlaylistService : addSong()
    deactivate PlaylistControllerAPI
    activate PlaylistService
    PlaylistService -> PlaylistRepository : addSong()
    deactivate PlaylistService
    alt Song exists 
        Playlist --> User : Song exists
    end
    deactivate Playlist
end
@enduml 