@startuml name 

title Αφαίρεση Τραγουδιού Από Λίστα Αναπαραγωγής

actor User
participant PlaylistView
participant PlaylistController
participant Playlist
participant PlaylistControllerAPI
participant PlaylistService
participant PlaylistRepository

activate PlaylistController
PlaylistController -> PlaylistView : display()
activate PlaylistView
deactivate PlaylistController
User -> PlaylistView : selectSong
PlaylistView -> PlaylistView : openSongOptions()
User -> PlaylistView : removeFromPlaylist
PlaylistView -> PlaylistController : removeFromPlaylist(int index)
activate PlaylistController
deactivate PlaylistView
PlaylistController -> Playlist : remove(songId, playlistId)
activate Playlist
deactivate PlaylistController
Playlist -> PlaylistControllerAPI : postRemoveSongById(songId,playlistId)
activate PlaylistControllerAPI
deactivate Playlist
PlaylistControllerAPI -> PlaylistService : removeSongById(songId, playlistId)
deactivate PlaylistControllerAPI
activate PlaylistService
deactivate PlaylistControllerAPI
PlaylistService -> PlaylistRepository : DELETE FROM playlist where song_id = songId and playlist_id = playlistId 
deactivate PlaylistService
@enduml