@startuml name

title Δημιουργία Λίστας Αναπαραγωγής

actor User
participant HomeView
participant HomeController
participant PlaylistView
participant PlaylistController
participant Playlist
participant PlaylistControllerAPI
participant PlaylistService
participant PlaylistRepository

activate HomeController
HomeController -> HomeView : display()
activate HomeView
User -> HomeView : showPlaylists()
HomeView -> HomeController : showPlaylists()
deactivate HomeView

HomeController -> PlaylistController : showPlaylists()
deactivate HomeController
activate PlaylistController
PlaylistController -> PlaylistView : display()
activate PlaylistView
User -> PlaylistView : createPlaylist()
PlaylistView -> PlaylistView : showPlaylistEditor()
User -> PlaylistView : playlist details
User -> PlaylistView : create()
PlaylistView -> PlaylistController : checkForDuplicateName()
PlaylistController -> Playlist : checkDuplicate()
activate Playlist
Playlist -> PlaylistControllerAPI : sendHTTPRequest()
activate PlaylistControllerAPI
PlaylistControllerAPI -> PlaylistService : processRequest()
activate PlaylistService
PlaylistService -> PlaylistRepository : runQuery()
activate PlaylistRepository
alt No Duplicate Playlists
    PlaylistRepository --> PlaylistService : return No Duplicates
    deactivate PlaylistRepository
    PlaylistService --> PlaylistControllerAPI : return No Duplicates
    deactivate PlaylistService
    PlaylistControllerAPI --> Playlist : return No Duplicates
    deactivate PlaylistControllerAPI
    Playlist --> PlaylistController : return No Duplicates
    deactivate Playlist
    PlaylistController --> PlaylistView : return No Duplicates
    User -> PlaylistView : createPlaylist()
    PlaylistView -> PlaylistController : createPlaylist() 
    PlaylistController -> Playlist : createPlaylist()
    activate Playlist
    Playlist -> PlaylistControllerAPI : sendHTTPRequest()
    activate PlaylistControllerAPI
    PlaylistControllerAPI -> PlaylistService : processRequest()
    activate PlaylistService
    PlaylistService -> PlaylistRepository : runQuery()
    activate PlaylistRepository
else Duplicate Found
    PlaylistRepository --> PlaylistService : return Duplicates Found
    deactivate PlaylistRepository
    PlaylistService --> PlaylistControllerAPI : return Duplicates Found
    deactivate PlaylistService
    PlaylistControllerAPI --> Playlist : return Duplicates Found
    deactivate PlaylistControllerAPI
    Playlist --> PlaylistController : return Duplicates Found
    deactivate Playlist
    PlaylistController --> PlaylistView : return Duplicates Found
    PlaylistView -> PlaylistView : showDuplicateFoundError()
end
@enduml