@startuml
title Music Streaming Application - Spring JPA Architecture (with Admin)

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam packageStyle rectangle

' =====================
' DOMAIN LAYER (ENTITIES)
' =====================

package "Model (Entities)" {

    ' -------- ACCOUNT HIERARCHY --------
    abstract class Account{
    # userID : String
    # username : String
    # password : String
    # email : String
    + Account()
    + Login(username : String, password : String) : void
    + Logout() : void
    + Register() : void
    + ViewProfile() : void
    + DownloadSong(songID : String) : void
    + FollowArtist(artistID : String) : void
    }
    

    class User{
    # userLibrary : Library
    - subscriptionType
    - userLibrary
    }
    class Artist{
    - artistName
    - bio
    }
    class Admin{
    + IssueStrike(userID : String) : void
    + CheckStrikes(userID : String) : void
    + RemoveStrike(userID : String) : void
    + BanUser(userID : String) : void
    + UnbanUser(userID : String) : void
    + ApproveUserToArtist(userID : String) : void
    }

    Account <|-- User
    Account <|-- Artist
    Account <|-- Admin

    ' -------- MUSIC CORE --------
    class Song {
    + songID : String
    - title : String
    - duration : double
    - releaseDate : Date
    }

    class Album {
    + albumID : String
    - title : String
    - releaseDate : Date
    }
    class Genre {
    - name : String
    }

    Artist "1" --> "0..*" Song : creates
    Artist "1" --> "0..*" Album : creates

    Album "1" *-- "1..*" Song

    Song "0..*" -- "0..*" Genre

    ' -------- PLAYLIST SYSTEM --------
    class Playlist {
    - playlistID : String
    - name : String
    - isPublic : boolean
    }
    

    User "1" --> "0..*" Playlist : owns
    Playlist "0..*" -- "0..*" Song

    ' -------- LIBRARY --------
    class Library{
        - playlists : List<Playlist>
        - albums : List<Albums>
        - songs : List<Song> 
        + AddSong(songID : String) : void
        + RemoveSong(songID : String) : void
        + AddPlaylist(playlistID : String) : void
        + RemovePlaylist(playlistID : String) : void
        + AddAlbum(albumID : String) : void
        + RemoveAlbum(albumID : String) : void
        + GetSongs() : List<Song>
        + GetPlaylists() : List<Playlist>
        + GetAlbums() : List<Album>
    }

    User "1" *-- "1" Library

    Library "0..*" --> Song
    Library "0..*" --> Album
    Library "0..*" --> Playlist

    ' -------- LISTENING HISTORY --------
    class ListeningHistory {
    - playedAt : DateTime
    }


    User "1" --> "0..*" ListeningHistory
    ListeningHistory --> Song

    ' -------- PLAYER --------
    class MusicPlayer{
    + OnPlayButtonClicked() : void
    + OnNextButtonClicked() : void
    + OnPreviousButtonClicked() : void
    + OnVolumChange() : void
    + OnSeek() : void
    + OnRepeatButtonClicked() : void
    + OnLikeButtonClicked() : void
    + OnShuffleButtonClicked() : void
    }
    MusicPlayer --> Song
}
' =====================
' PRESENTATION LAYER
' =====================
package "Controllers (UI)" {

    class MainController{
    + main(args : String[]) : void
    }

    class MusicPlayerController {
    - musicPlayerView : MusicPlayerView
    - musicPlayer : MusicPlayer
    + MusicPlayerController()
    + OnPlayButtonClicked() : void
    + OnNextButtonClicked() : void
    + OnPreviousButtonClicked() : void
    + OnVolumChange() : void
    + OnSeek() : void
    + OnRepeatButtonClicked() : void
    + OnLikeButtonClicked() : void
    + OnShuffleButtonClicked() : void
    }
    class HomeController{
    - homeView : HomeView
    + HomeController(view : HomeView)
    + LoadHomeData() : void
    + OnAssetClick(asset : Object) : void
    }
    class LibraryController{
    - libraryView : LibraryView
    - library : Library
    + LibraryController(view : LibraryView, library : Library)   
    + OnSelection() : void
    + LoadAssets() : void
    }
    class TopBarController{
    - tobBarView : TopBarView
    + TobBarController(view : TopBarView)
    + OnSearchButtonClicked() : void
    + OnBackButtonClicked() : void
    + OnForwardButtonClicked() : void
    + OnProfileButtonClicked() : void
    }
    class PlaylistController{
    - playlistView : PLaylistView
    + PlaylistController(view : PlaylistView)
    }
}

package "Views" {
    class MusicPlayerView{
    - musicPlayerController : MusicPlayerController
    + MusicPlayerView()
    + SetController(newController : MusicPlayerController) : void
    + OnPlayButtonClicked() : void
    + OnNextButtonClicked() : void
    + OnPreviousButtonClicked() : void
    + OnVolumChange() : void
    + OnSeek() : void
    + OnRepeatButtonClicked() : void
    + OnLikeButtonClicked() : void
    + OnShuffleButtonClicked() : void
    }
    class HomeView{
    - homeController : HomeController
    + HomeView()
    + SetController(newController : HomeController) : void
    + OnAssetClick(asset : Object) : void
    }
    class LibraryView{
    - libraryController : LibraryController
    + LibraryView()
    + SetController(newController : LibraryController) : void
    + OnSelection() : void
    + LoadAssets() : void
    }
    class TopBarView{
    - topBarController : TopBarController
    + TopBarView()
    + SetController(newController : TobBarController) : void
    + OnSearchButtonClicked() : void
    + OnBackButtonClicked() : void
    + OnForwardButtonClicked() : void
    + OnProfileButtonClicked() : void
    }
    class PlaylistView{
    - playlistController : PlaylistController
    + PlaylistView()
    + SetController(newController : PlaylistController) : void
    + DisplayPlaylist() : void
    }
}

' UI links
MusicPlayerController -- MusicPlayer
MusicPlayerView -- MusicPlayerController
MainController -- MusicPlayerController

HomeView -- HomeController
MainController -- HomeController

LibraryView -- LibraryController
MainController -- LibraryController

PlaylistView -- PlaylistController
PlaylistController -- MainController

TopBarView -- TopBarController
MainController -- Account

' =====================
' SPRING BACKEND
' =====================

package "Spring Backend" {

    ' Controllers (REST)
    class AccountController
    class UserController
    class ArtistController
    class AdminController
    class SongController
    class AlbumController
    class PlaylistControllerAPI
    class LibraryControllerAPI
    class GenreController
    class ListeningHistoryController

    ' Services
    class AccountService
    class UserService
    class ArtistService
    class AdminService
    class SongService
    class AlbumService
    class PlaylistService
    class LibraryService
    class GenreService
    class ListeningHistoryService

    ' Repositories (JPA)
    class AccountRepository
    class UserRepository
    class ArtistRepository
    class AdminRepository
    class SongRepository
    class AlbumRepository
    class PlaylistRepository
    class LibraryRepository
    class GenreRepository
    class ListeningHistoryRepository
}

' Controller → Service
AccountController --> AccountService
UserController --> UserService
ArtistController --> ArtistService
AdminController --> AdminService
SongController --> SongService
AlbumController --> AlbumService
PlaylistControllerAPI --> PlaylistService
LibraryControllerAPI --> LibraryService
GenreController --> GenreService
ListeningHistoryController --> ListeningHistoryService


' Service → Repository
AccountService --> AccountRepository
UserService --> UserRepository
ArtistService --> ArtistRepository
AdminService --> AdminRepository
SongService --> SongRepository
AlbumService --> AlbumRepository
PlaylistService --> PlaylistRepository
LibraryService --> LibraryRepository
GenreService --> GenreRepository
ListeningHistoryService --> ListeningHistoryRepository

' Repository → Entities
AccountRepository --> Account
UserRepository --> User
ArtistRepository --> Artist
AdminRepository --> Admin
SongRepository --> Song
AlbumRepository --> Album
PlaylistRepository --> Playlist
LibraryRepository --> Library
GenreRepository --> Genre
ListeningHistoryRepository --> ListeningHistory

@enduml