/*
 * This source file was generated by the Gradle 'init' task
 */
package tunix;

import org.junit.jupiter.api.Test;

import tunix.app.TunixApp;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        TunixApp classUnderTest = new TunixApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
