/*
 * This source file was generated by the Gradle 'init' task
 */
package tunix;

import org.junit.jupiter.api.Test;

import tunix.app.AppLauncher;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        AppLauncher classUnderTest = new AppLauncher();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
