@startuml AddSongToPlaylist

title Add Song To Playlist

actor User

participant MainPanel
participant SearchView
participant SearchController
participant MusicView
participant MusicController
participant PlaylistService
participant PlaylistApi
participant ApiClient
participant PlaylistBackendController
participant PlaylistBackendService
participant PlaylistBackendRepository


participant EventBus

ref over SearchView, SearchController
SearchSong
end ref
activate SearchView
User -> SearchView : right click on song
SearchView -> SearchView : showSongContextMenu()
activate SearchView
User -> SearchView : click on "Add to Playlist"
SearchView -> SearchView : showPlaylistSelectionPopUp()
activate SearchView
User -> SearchView : select playlist
SearchView -> SearchController : checkForDuplicates(playlistId, songId)
activate SearchController
SearchController -> PlaylistService : checkForDuplicateSong(playlistId, songId)
activate PlaylistService
PlaylistService -> PlaylistApi : checkForDuplicateSong(playlistId, songId)
activate PlaylistApi
PlaylistApi -> ApiClient : post(playlist/checkForDuplicate, playlistId, songId)
'will need to find an alternative to send both ids with one argument
activate ApiClient
ApiClient -> PlaylistBackendController : checkForDuplicateSong(playlistId, songId)
activate PlaylistBackendController
PlaylistBackendController -> PlaylistBackendService : checkForDuplicateSong(playlistId, songId)
activate PlaylistBackendService
PlaylistBackendService -> PlaylistBackendRepository : checkForDuplicateSong(playlistId, songId)
activate PlaylistBackendRepository
PlaylistBackendRepository --> PlaylistBackendService : hasDuplicate
deactivate PlaylistBackendRepository
PlaylistBackendService --> PlaylistBackendController : hasDuplicate
deactivate PlaylistBackendService
PlaylistBackendController --> ApiClient : hasDuplicate
deactivate PlaylistBackendController
ApiClient --> PlaylistApi : hasDuplicate
deactivate ApiClient
PlaylistApi --> PlaylistService : hasDuplicate
deactivate PlaylistApi
PlaylistService --> SearchController : hasDuplicate
deactivate PlaylistService
alt !hasDuplicate
SearchController -> PlaylistService : addToPlaylist(playlistId, songId)
activate PlaylistService
PlaylistService -> PlaylistApi : addToPlaylist(playlistId, songId)
activate PlaylistApi
PlaylistApi -> ApiClient : post(playlist/addToPlaylist, playlistId, songId)
'will need to find an alternative to send both ids with one argument
activate ApiClient
ApiClient -> PlaylistBackendController : addToPlaylist(playlistId, songId)
activate PlaylistBackendController
PlaylistBackendController -> PlaylistBackendService : addToPlaylist(playlistId, songId)
activate PlaylistBackendService
PlaylistBackendService -> PlaylistBackendRepository : addToPlaylist(playlistId, songId)
activate PlaylistBackendRepository
PlaylistBackendRepository --> PlaylistBackendService : updated playlist
deactivate PlaylistBackendRepository
PlaylistBackendService --> PlaylistBackendController : updated playlist
deactivate PlaylistBackendService
PlaylistBackendController --> ApiClient : updated playlist
deactivate PlaylistBackendController
ApiClient --> PlaylistApi : updated playlist
deactivate ApiClient
PlaylistApi --> PlaylistService : updated playlist
deactivate PlaylistApi
PlaylistService --> SearchController : updated playlist
deactivate PlaylistService
SearchController -> EventBus : publish switchToMusicView(MusicView, playlist)
activate EventBus
EventBus -> MainPanel : switchToMusicView(playlist)
activate MainPanel
deactivate EventBus
create MusicController
MainPanel -->> MusicController : new(playlist)
activate MusicController
deactivate MainPanel
create MusicView
MusicController -->> MusicView : new()
activate MusicView
MusicController -> MusicView : display(playlistData)

else hasDuplicate
SearchController -> SearchView : showDuplicateExistsPopUp()
end

@enduml