@startuml ApproveOrRejectArtistRequest

title Approve Or Reject Artist Request

actor Admin

participant AdminDashdoardView
participant AdminDashdoardController
participant ArtistRequestService
participant ArtistRequestApiClient
participant ApiClient
participant ArtistRequestBackendController
participant ArtistRequestBackendService
participant ArtistRequestBackendRepository

activate AdminDashdoardView
Admin -> AdminDashdoardView : clicks on "Artist Account Applications"
AdminDashdoardView -> AdminDashdoardView : showArtistAccountApplications()
Admin -> AdminDashdoardView : selects an application
AdminDashdoardView -> AdminDashdoardController : getApplicationDetails(applicationId)
activate AdminDashdoardController
AdminDashdoardController -> ArtistRequestService : getApplicationDetails(applicationId)
activate ArtistRequestService
ArtistRequestService -> ArtistRequestApiClient : getApplicationDetails(applicationId)
activate ArtistRequestApiClient
ArtistRequestApiClient -> ApiClient : post(artistRequest/getRequests, applicationId)
activate ApiClient
ApiClient -> ArtistRequestBackendController : getApplicationDetails(applicationId)
activate ArtistRequestBackendController
ArtistRequestBackendController -> ArtistRequestBackendService : getApplicationDetails(applicationId)
activate ArtistRequestBackendService
ArtistRequestBackendService -> ArtistRequestBackendRepository : getApplicationDetails(applicationId)
activate ArtistRequestBackendRepository
ArtistRequestBackendRepository --> ArtistRequestBackendService : return application details
deactivate ArtistRequestBackendRepository
ArtistRequestBackendService --> ArtistRequestBackendController : return application details
deactivate ArtistRequestBackendService
ArtistRequestBackendController --> ApiClient : return application details
deactivate ArtistRequestBackendController
ApiClient --> ArtistRequestApiClient : return application details
deactivate ApiClient
ArtistRequestApiClient --> AdminDashdoardController : return application details
deactivate ArtistRequestApiClient
AdminDashdoardController -> AdminDashdoardView : showApplicationDetails(applicationDetails)
deactivate AdminDashdoardController
alt Admin approves Request
    Admin -> AdminDashdoardView : Approve Request
else Admin rejects Request
    Admin -> AdminDashdoardView : Reject Request
end
AdminDashdoardView -> AdminDashdoardController : saveResponse(adminRes, applicationId)
activate AdminDashdoardController
AdminDashdoardController -> ArtistRequestService : saveResponse(adminRes, applicationId)
activate ArtistRequestService
ArtistRequestService -> ArtistRequestApiClient : saveResponse(adminRes, applicationId)
activate ArtistRequestApiClient
ArtistRequestApiClient -> ApiClient : post(artistRequest/saveRequest, adminRes, applicationId)
activate ApiClient
ApiClient -> ArtistRequestBackendController : getApplicationDetails(applicationId)
activate ArtistRequestBackendController
ArtistRequestBackendController -> ArtistRequestBackendService : saveResponse(adminRes, applicationId)
activate ArtistRequestBackendService
ArtistRequestBackendService -> ArtistRequestBackendRepository : saveResponse(adminRes, applicationId)
activate ArtistRequestBackendRepository
ArtistRequestBackendRepository --> ArtistRequestBackendService : return success
deactivate ArtistRequestBackendRepository
ArtistRequestBackendService --> ArtistRequestBackendController : return success
deactivate ArtistRequestBackendService
ArtistRequestBackendController --> ApiClient : return success
deactivate ArtistRequestBackendController
ApiClient --> ArtistRequestApiClient : return success
deactivate ApiClient
ArtistRequestApiClient --> AdminDashdoardController : return success
deactivate ArtistRequestApiClient



@enduml