@startuml CancelPremium

title Cancel Premium

actor User

participant UserProfileView
participant UserProfileController
participant UserService
participant UserApi
participant ApiService
participant UserBackendController
participant UserBackendService
participant UserBackendRepository

database DB

activate UserProfileView
User -> UserProfileView : clicks on "Cancel Premium"
UserProfileView -> UserProfileController : updatePremiumStatus(userId,false)
activate UserProfileController
UserProfileController -> UserService : updatePremiumStatus(userId,false)
activate UserService
UserService -> UserApi : updatePremiumStatus(userId,false)
activate UserApi
UserApi -> ApiService : post(user/updatePremiumStatus,userId,false)
activate ApiService
ApiService -> UserBackendController : updatePremiumStatus(userId,false)
activate UserBackendController
UserBackendController -> UserBackendService : updatePremiumStatus(userId,false)
activate UserBackendService
UserBackendService -> UserBackendRepository : updatePremiumStatus(userId,false)
activate UserBackendRepository
UserBackendRepository -> DB : run mySQL query
DB --> UserBackendRepository : return success
UserBackendRepository --> UserBackendService : return success
deactivate UserBackendRepository
UserBackendService -> UserBackendController : return success
deactivate UserBackendService
UserBackendController --> ApiService : return success
deactivate UserBackendController
ApiService --> UserApi : return success
deactivate ApiService
UserApi --> UserService : return success
deactivate UserApi
UserService --> UserProfileController : return success
deactivate UserService
UserProfileController -> UserProfileView : showSuccessMessage("Premium Subscription Canceled successfully")

@enduml