@startuml PlaySongInPlaylistOrAlbum

title Play Song in Playlist or Album

actor User

participant MusicView
participant MusicController
participant MusicPlayerView
participant MusicPlayerController
participant SongService
participant SongApiClient
participant ApiService
participant SongBackendController
participant SongBackendService
participant SongBackendRepository

participant EventBus

database DB

activate MusicPlayerView
ref over MusicView, MusicController
SelectPlaylist / SelectAlbum && select Album
end ref
activate MusicView
User -> MusicView : clicks on song
MusicView -> MusicController : onSongSelected(songOrder) 
'SongOrder is the list of songs to be played
activate MusicController
MusicController -> EventBus : publish(SongSelectedEvent,songOrder)
activate EventBus
EventBus -> MusicPlayerController : setCurrentSongOrder(songOrder)
activate MusicPlayerController
alt User clicks shuffle toggle
    User -> MusicPlayerView : clicks on shuffle
    MusicPlayerView -> MusicPlayerController : selectRandomSong()
end
User -> MusicPlayerView : clicks on "Play"
MusicPlayerView -> MusicPlayerController : getSongById(songId)
MusicPlayerController -> SongService : getSongById(songId)
activate SongService
SongService -> SongApiClient : getSongById(songId)
activate SongApiClient
SongApiClient -> ApiService : post(/songs/getById, songId)
activate ApiService
ApiService -> SongBackendController : getSongById(songId)
activate SongBackendController
SongBackendService -> SongBackendRepository : getSongById(songId)
activate SongBackendRepository
SongBackendRepository -> DB : run mySQL query
DB --> SongBackendRepository : return song
SongBackendRepository --> SongBackendService : return song
deactivate SongBackendRepository
SongBackendService --> SongBackendController : return song
deactivate SongBackendService
SongBackendController --> ApiService : return song
deactivate SongBackendController
Api --> SongService : return song
SongService --> MusicPlayerController : return song
MusicPlayerController ->> MusicPlayerView : updateView()


@enduml