@startuml SearchPlaylist

title Search Playlist

actor User

participant MainPanel
participant TopBarView
participant TopBarController
participant SearchView
participant SearchController
participant PlaylistService
participant PlaylistApi
participant ApiService
participant PlaylistBackendController
participant PlaylistBackendService
participant PlaylistBackendRepository

database DB

participant EventBus

activate TopBarView
User -> TopBarView : writes search query
User -> TopBarView : selects Playlist
User -> TopBarView : clicks on "Search"
TopBarView -> TopBarController : search(query,searchType)
deactivate TopBarView
activate TopBarController
TopBarController -> PlaylistService : searchPlaylistByName(query)
deactivate TopBarController
activate PlaylistService
PlaylistService -> PlaylistApi : searchPlaylistByName(query)
activate PlaylistApi
PlaylistApi -> ApiService : post("playlist/getByName", query)
activate ApiService
ApiService -> PlaylistBackendController : searchPlaylistByName(query)
activate PlaylistBackendController
PlaylistBackendController -> PlaylistBackendService : searchPlaylistByName(query)
activate PlaylistBackendService
PlaylistBackendService -> PlaylistBackendRepository : searchPlaylistByName(query)
activate PlaylistBackendRepository
PlaylistBackendRepository -> DB : run mySQL query
DB --> PlaylistBackendRepository : return results
PlaylistBackendRepository --> PlaylistBackendService : return results
deactivate PlaylistBackendRepository
PlaylistBackendService --> PlaylistBackendController : return results
deactivate PlaylistBackendService
PlaylistBackendController --> ApiService : return results
deactivate PlaylistBackendController
ApiService --> PlaylistApi : return results
deactivate ApiService
PlaylistApi --> PlaylistService : return results
deactivate PlaylistApi
PlaylistService --> TopBarController : return results
deactivate PlaylistService
TopBarController -> EventBus : publish SwitchMainScreenEvent, SearchController
activate EventBus
EventBus -> MainPanel : switchMainScreen(SearchController)
deactivate EventBus
activate MainPanel
create SearchController
MainPanel -->> SearchController : new(results)
deactivate MainPanel
activate SearchController
create SearchView
SearchController -->> SearchView : new()
activate SearchView
SearchController -> SearchView : showSearchResults(results)

@enduml