@startuml Approve / Reject Artist Request

title Approve Reject Artist Request

actor Admin
participant AdminView
participant AdminController
participant ArtistRequestService
participant ArtistRequestAPI
participant ApiClient
participant ArtistRequestBackendController
participant ArtistRequestBackendService
participant ArtistRequestBackendRepository
database Database

activate AdminView
Admin -> AdminView : Click on "Artist Account Applications"
AdminView -> AdminController : onArtistRequestsClicked()
activate AdminController
AdminController -> ArtistRequestService : onArtistRequestsClicked()
activate ArtistRequestService
ArtistRequestService -> ArtistRequestService: getArtistRequests()
ArtistRequestService -> ArtistRequestAPI : getAllArtistRequests()
activate ArtistRequestAPI
ArtistRequestAPI -> ApiClient : get "/artist-requests/getAll", new TypeReference<ApiResponse<List<ArtistRequestResponse>>>() {}
activate ApiClient
ApiClient -> ArtistRequestBackendController : GET /artist-requests/getAll
activate ArtistRequestBackendController
ArtistRequestBackendController -> ArtistRequestBackendService : getAllArtistRequests()
activate ArtistRequestBackendService
ArtistRequestBackendService -> ArtistRequestBackendRepository : getAllArtistRequests()
activate ArtistRequestBackendRepository
ArtistRequestBackendRepository -> Database : findAllArtists();
Database --> ArtistRequestBackendRepository : Return list of artist requests
ArtistRequestBackendRepository --> ArtistRequestBackendService : Return list of artist requests
deactivate ArtistRequestBackendRepository
ArtistRequestBackendService --> ArtistRequestBackendService : map to ArtistRequestResponse
ArtistRequestBackendService --> ArtistRequestBackendController : Return  ArtistRequestResponse list
deactivate ArtistRequestBackendService
ArtistRequestBackendController --> ApiClient : Return ArtistRequestResponse list
deactivate ArtistRequestBackendController
ApiClient --> ArtistRequestAPI : Return ArtistRequestResponse list
deactivate ApiClient
ArtistRequestAPI --> ArtistRequestService : Return ArtistRequestResponse list
deactivate ArtistRequestAPI
ArtistRequestService --> ArtistRequestService : map to ArtistRequest list
ArtistRequestService --> AdminController : Return list of artist requests
deactivate ArtistRequestService
AdminController --> AdminView : Return list of artist requests
AdminView -> AdminView : displayArtistRequests()
AdminView -> Admin : Show list of artist requests
deactivate AdminController
Admin -> AdminView : Click on an artist request
AdminView -> AdminView : onArtistRequestShowDetailsClicked(artistRequest)
AdminView -> AdminView : displayArtistRequestDetails(artistRequest)
AdminView -> Admin : Show artist request details
Admin -> AdminView : Click "Approve" or "Reject"
alt Approve
    AdminView -> AdminController : onApproveArtistRequestClicked(requestId)
    activate AdminController
    AdminController -> ArtistRequestService : approveArtistRequest(requestId)
    activate ArtistRequestService
    ArtistRequestService -> ArtistRequestAPI : approveArtistRequest(requestId)
    activate ArtistRequestAPI
    ArtistRequestAPI -> ApiClient : POST /artist-requests/approve/{requestId}
    activate ApiClient
    ApiClient -> ArtistRequestBackendController : POST /artist-requests/approve/{requestId}
    activate ArtistRequestBackendController
    ArtistRequestBackendController -> ArtistRequestBackendController : approveArtistRequest(requestId)
    ArtistRequestBackendController -> ArtistRequestBackendService : approveArtistRequest(requestId)
    activate ArtistRequestBackendService
    ArtistRequestBackendService -> ArtistRequestBackendRepository : findById(requestId)
    activate ArtistRequestBackendRepository
    ArtistRequestBackendRepository -> Database : findById(requestId)
    Database --> ArtistRequestBackendRepository : Return artist request
    ArtistRequestBackendRepository -> ArtistRequestBackendService : Return artist request
    deactivate ArtistRequestBackendRepository
    ArtistRequestBackendService -> ArtistRequestBackendService : setStatus(Approved)
    ArtistRequestBackendService -> ArtistRequestBackendRepository : save(artistRequest)
    activate ArtistRequestBackendRepository
    ArtistRequestBackendRepository -> Database : Query to modify the database
    Database -> ArtistRequestBackendRepository : return success
    ArtistRequestBackendRepository -> ArtistRequestBackendService : return success
    deactivate ArtistRequestBackendRepository
    ArtistRequestBackendService -> ArtistRequestBackendController : return ApiResponse
    deactivate ArtistRequestBackendService
    ArtistRequestBackendController -> ApiClient : return ApiResponse
    deactivate ArtistRequestBackendController
    ApiClient -> ArtistRequestAPI: returnApiReponse
    deactivate ApiClient
    ArtistRequestAPI -> ArtistRequestService : return ApiResponse
    deactivate ArtistRequestAPI
    ArtistRequestService -> AdminController : return success
    deactivate ArtistRequestService
    AdminController -> AdminView : showMessage("Approved")
    deactivate AdminController 
    AdminView -> Admin : Show approved message
else Reject
    AdminView -> AdminController : onRejectArtistRequestClicked(requestId)
    activate AdminController
    AdminController -> ArtistRequestService : rejectArtistRequest(requestId)
    activate ArtistRequestService
    ArtistRequestService -> ArtistRequestAPI : rejectArtistRequest(requestId)
    activate ArtistRequestAPI
    ArtistRequestAPI -> ApiClient : POST /artist-requests/reject/{requestId}
    activate ApiClient
    ApiClient -> ArtistRequestBackendController : POST /artist-requests/reject/{requestId}
    activate ArtistRequestBackendController
    ArtistRequestBackendController -> ArtistRequestBackendController : rejectArtistRequest(requestId)
    ArtistRequestBackendController -> ArtistRequestBackendService : rejectArtistRequest(requestId)
    activate ArtistRequestBackendService
    ArtistRequestBackendService -> ArtistRequestBackendRepository : findById(requestId)
    activate ArtistRequestBackendRepository
    ArtistRequestBackendRepository -> Database : findById(requestId)
    Database --> ArtistRequestBackendRepository : Return artist request
    ArtistRequestBackendRepository -> ArtistRequestBackendService : Return artist request
    deactivate ArtistRequestBackendRepository
    ArtistRequestBackendService -> ArtistRequestBackendService : setStatus(Rejected)
    ArtistRequestBackendService -> ArtistRequestBackendRepository : save(artistRequest)
    activate ArtistRequestBackendRepository
    ArtistRequestBackendRepository -> Database : Query to modify the database
    Database -> ArtistRequestBackendRepository : return success
    ArtistRequestBackendRepository -> ArtistRequestBackendService : return success
    deactivate ArtistRequestBackendRepository
    ArtistRequestBackendService -> ArtistRequestBackendController : return ApiResponse
    deactivate ArtistRequestBackendService
    ArtistRequestBackendController -> ApiClient : return ApiResponse
    deactivate ArtistRequestBackendController
    ApiClient -> ArtistRequestAPI: returnApiReponse
    deactivate ApiClient
    ArtistRequestAPI -> ArtistRequestService : return ApiResponse
    deactivate ArtistRequestAPI
    ArtistRequestService -> AdminController : return success
    deactivate ArtistRequestService
    AdminController -> AdminView : showMessage("Reject")
    deactivate AdminController 
    AdminView -> Admin : Show reject message
end

@enduml
