@startuml CreatePlaylist
actor User as user 
participant LibraryView as libraryView
participant LibraryController as libraryController
participant PlaylistService as playlistService
participant PlaylistApiClient as playlistApi
participant ApiClient as apiClient
participant PlaylistBackendController as playlistBackendController
participant PlaylistBackendService as playlistBackendService
participant PlaylistBackendRepository as playlistBackendRepository
database Database as database
participant Eventbus as eventbus
participant PlaylistController as playlistController
participant PlaylistView as playlistView 

user -> libraryView: "Right click on library"
activate libraryView
libraryView -> libraryView : onRightClickOnLibrary()
libraryView -> libraryView : showLibraryOptions()
libraryView -> user : "Show user library options"
user -> libraryView : "Select 'Create Playlist'"
libraryView -> libraryView : onCreatePlaylistClicked()
libraryView -> libraryView : showPlaylistCreationMenu()
libraryView -> user : "Show user creation menu" 
user -> libraryView : "User enter details and presses confirm"
libraryView -> libraryView : onPlaylistCreateConfirmClicked()
deactivate libraryView
libraryView -> libraryController : createPlaylist(playlistCreateRequest)
activate libraryController
libraryController -> playlistService : createPlaylist(playlistCreateRequest, libraryAssets)
activate playlistService
playlistService -> playlistService : checkDuplicateName(playlistCreateRequest, libraryAssets)
alt if unique
    playlistService -> playlistApi : createPlaylist(playlistCreateRequest)
    activate playlistApi 
    playlistApi -> apiClient : post("/playlists/create", playlistCreateRequest, PlaylistResponse.class)
    activate apiClient

    apiClient -> playlistBackendController : POST /playlist/create
    activate playlistBackendController

    playlistBackendController -> playlistBackendService : createPlaylist(playlistCreateRequest)
    activate playlistBackendService

    playlistBackendService -> playlistBackendRepository : save(playlistCreateRequest.toPlaylistEntity())
    activate playlistBackendRepository 
    playlistBackendRepository -> database : Insert playlist to user's playlists table
    database -> playlistBackendRepository : return success
    playlistBackendRepository -> playlistBackendService : return success
    deactivate playlistBackendRepository 
    playlistBackendService -> playlistBackendController : return success
    deactivate playlistBackendService
    playlistBackendController -> apiClient : return succes ApiResponse
    deactivate playlistBackendController
    apiClient -> playlistApi : return success ApiResponse
    deactivate apiClient
    playlistApi -> playlistService : return true
    deactivate playlistApi
    playlistService -> libraryController : return true
    deactivate playlistService
    libraryController -> libraryView : showPlaylistCreationSuccess()
    libraryView -> user : "Show user created succesdully message"

    libraryController -> eventbus : publish(new PlaylistCreatedEvent(playlist))
    deactivate libraryController
    deactivate libraryView
    activate eventbus

    eventbus -> playlistController : "PlaylistCreatedEvent happened"
    activate playlistController

    deactivate eventbus
    playlistController -> playlistView : displayPlaylist(playlist)
    deactivate playlistController 
    playlistView -> user : "Show created playlist view"
else if duplicate found
    activate playlistService
    playlistService -> libraryController : showDuplicateNameError()
    deactivate playlistService
    activate libraryController
    libraryController -> libraryView : showDuplcateNameError()
    deactivate libraryController
    activate libraryView
    libraryView -> user : "Show duplicate name error"
    deactivate libraryView
end
@enduml