@startuml name

title Check Statistics

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Καλλιτέχνης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Μενού_Ρυθμίσεων_Προφίλ_Καλλιτέχνη
boundary Οθόνη_Statistics

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Άντληση_Δεδομένων_Καλλιτέχνη
control Υπολογισμός_Στατιστικών
control Επιλογή_Στοιχεία_Πλοήγησης

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων

' =====================================================
' INTERACTIONS
' =====================================================

Καλλιτέχνης --> Μενού_Πλοήγησης
Μενού_Πλοήγησης --> Επιλογή_Στοιχεία_Πλοήγησης
Επιλογή_Στοιχεία_Πλοήγησης --> Μενού_Ρυθμίσεων_Προφίλ_Καλλιτέχνη : Επιλογή εικόνας προφίλ Καλλιτέχνη
Μενού_Ρυθμίσεων_Προφίλ_Καλλιτέχνη -->  Άντληση_Δεδομένων_Καλλιτέχνη
Άντληση_Δεδομένων_Καλλιτέχνη -- Βάση_Δεδομένων 
Άντληση_Δεδομένων_Καλλιτέχνη --> Υπολογισμός_Στατιστικών
Υπολογισμός_Στατιστικών --> Οθόνη_Statistics : Το σύστημα δείχνει τα στατιστικά
Οθόνη_Statistics --> Καλλιτέχνης

@enduml