@startuml name

title Create Playlist

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Ίδιο_Όνομα_Popup
boundary Επιτυχής_Δημιουργία_Popup
boundary Playlist_Editor

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Επιστροφη_στο_Editor
control Έλεγξε_για_ίδιο_όνομα
control Δημιούργησε_Λίστα_Αναπαραγωγής
control Playlist_Options

entity Βάση_Δεδομένων

' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Μενού_Πλοήγησης
Μενού_Πλοήγησης --> Playlist_Options : Eπιλέγει Δημιουργία νέας λίστας Αναπαραγωγής
Playlist_Options --> Playlist_Editor 
Γενικός_Χρήστης --> Playlist_Editor : Εισάγει στοιχεία λίστας αναπαραγωγής
Playlist_Editor --> Έλεγξε_για_ίδιο_όνομα
Έλεγξε_για_ίδιο_όνομα --> Δημιούργησε_Λίστα_Αναπαραγωγής : Δεν υπάρχει
Δημιούργησε_Λίστα_Αναπαραγωγής -- Βάση_Δεδομένων
Δημιούργησε_Λίστα_Αναπαραγωγής --> Επιτυχής_Δημιουργία_Popup
Έλεγξε_για_ίδιο_όνομα --> Ίδιο_Όνομα_Popup : Υπάρχει
Ίδιο_Όνομα_Popup --> Επιστροφη_στο_Editor
Επιστροφη_στο_Editor --> Playlist_Editor
Επιτυχής_Δημιουργία_Popup --> Γενικός_Χρήστης
Ίδιο_Όνομα_Popup --> Γενικός_Χρήστης

@enduml
