@startuml name

title Download Songs

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================


boundary Μενού_Επιλογών_Τραγουδιού
boundary Όχι_Αρκετός_Χώρος_Popup
boundary Download_Button

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Έλεγχος_Premium
control Έλεγχος_Χώρου
control Κατέβασμα_Τραγουδιού
control Εμφανίση_Μενού_Επιλογών_Τραγουδιού


' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων
entity Τοπικό_Σύστημα_Αρχείων

' =====================================================
' USE CASES
' =====================================================

usecase Αναζήτηση_Tραγουδιού_Search_Content


' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Αναζήτηση_Tραγουδιού_Search_Content
Αναζήτηση_Tραγουδιού_Search_Content --> Μενού_Επιλογών_Τραγουδιού: επιλέγει το τραγούδι που θέλει
Μενού_Επιλογών_Τραγουδιού --> Έλεγχος_Premium
Έλεγχος_Premium --> Download_Button : Premium =/= 0 : show
Γενικός_Χρήστης --> Download_Button
Download_Button --> Έλεγχος_Χώρου
Έλεγχος_Χώρου <--> Τοπικό_Σύστημα_Αρχείων : Ελέγχει χώρο
Έλεγχος_Χώρου --> Κατέβασμα_Τραγουδιού : χώρος Αρκετός
Κατέβασμα_Τραγουδιού --> Τοπικό_Σύστημα_Αρχείων : Βρίσκει filepath downloads, τραγούδι κατεβαίνει
Κατέβασμα_Τραγουδιού <--> Βάση_Δεδομένων : Fetch song file + metadata
Έλεγχος_Χώρου --> Όχι_Αρκετός_Χώρος_Popup : όχι αρκετός χώρος
Όχι_Αρκετός_Χώρος_Popup --> Γενικός_Χρήστης
Όχι_Αρκετός_Χώρος_Popup --> Εμφανίση_Μενού_Επιλογών_Τραγουδιού : Εμφάνιση μενού επιλογών τραγουδιού
Εμφανίση_Μενού_Επιλογών_Τραγουδιού --> Μενού_Επιλογών_Τραγουδιού

@enduml