@startuml name

title Premium Purchase

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Οθόνη_Premium
boundary Οθόνη_Επιτυχίας_Πληρωμής
boundary Error_Payment_Popup
boundary Ερώτηση_Αυτόματης_Ανανέωσης



' =====================================================
' CONTROL OBJECTS
' =====================================================

control Επιλογή_Στοιχεία_Πλοήγησης
control Εμφάνηση_Ερώτησης_Αυτόματης_Ανανέωσης
control Αποθήκευση_Πληροφοριών_Αυτόματης_Ανανέωσης

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων


' =====================================================
' USE CASES
' =====================================================

usecase Payment_Through_Bank_Account

' =====================================================
' INTERACTIONS
' =====================================================
Γενικός_Χρήστης --> Μενού_Πλοήγησης 
Μενού_Πλοήγησης --> Επιλογή_Στοιχεία_Πλοήγησης
Επιλογή_Στοιχεία_Πλοήγησης --> Οθόνη_Premium
Γενικός_Χρήστης --> Οθόνη_Premium : Επιλέγει Premium Πακέτο
Οθόνη_Premium --> Payment_Through_Bank_Account
Payment_Through_Bank_Account --> Οθόνη_Επιτυχίας_Πληρωμής : Επιτυχής
Payment_Through_Bank_Account --> Error_Payment_Popup : Ανεπιτυχής
Error_Payment_Popup --> Γενικός_Χρήστης
Error_Payment_Popup --> Οθόνη_Premium
' Δε ξέρω τι να βάλω για control εδώ, 150 render δεν έχουν νόημα
Οθόνη_Επιτυχίας_Πληρωμής --> Εμφάνηση_Ερώτησης_Αυτόματης_Ανανέωσης 
Εμφάνηση_Ερώτησης_Αυτόματης_Ανανέωσης --> Ερώτηση_Αυτόματης_Ανανέωσης
Γενικός_Χρήστης --> Ερώτηση_Αυτόματης_Ανανέωσης : Επιλέγει αν θέλει αυτόματη ανανέωση ή όχι
Ερώτηση_Αυτόματης_Ανανέωσης --> Αποθήκευση_Πληροφοριών_Αυτόματης_Ανανέωσης 
Αποθήκευση_Πληροφοριών_Αυτόματης_Ανανέωσης --> Βάση_Δεδομένων 




@enduml