@startuml name

title Search Content

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Γενικός_Χρήστης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Οθόνη_Αναζήτησης 

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Έλεγχος_Τύπου_Περιεχομένου
control Αναζήτηση_Τραγουδιών_Τίτλος
control Αναζήτηση_Άλμπουμ_Τίτλος
control Αναζήτηση_Τραγουδιών_Άλμπουμ 
control Αναζήτηση_Καλλιτέχνη_Τίτλος
control Αναζήτηση_Τραγουδιών_Καλλιτέχνη
control Επιλογή_Στοιχεία_Πλοήγησης

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων

' =====================================================
' INTERACTIONS
' =====================================================

Γενικός_Χρήστης --> Μενού_Πλοήγησης 
Μενού_Πλοήγησης --> Επιλογή_Στοιχεία_Πλοήγησης
Επιλογή_Στοιχεία_Πλοήγησης --> Οθόνη_Αναζήτησης : Επιλέγει Αναζήτηση Περιεχομένου
Γενικός_Χρήστης --> Οθόνη_Αναζήτησης
Οθόνη_Αναζήτησης --> Έλεγχος_Τύπου_Περιεχομένου : Εισαγάγει αναζήτηση και Τύπο περιεχομένου

Έλεγχος_Τύπου_Περιεχομένου --> Αναζήτηση_Τραγουδιών_Τίτλος : Τύπος-Τραγούδι
Έλεγχος_Τύπου_Περιεχομένου --> Αναζήτηση_Καλλιτέχνη_Τίτλος : Τύπος-Καλλιτέχνης
Έλεγχος_Τύπου_Περιεχομένου --> Αναζήτηση_Άλμπουμ_Τίτλος : Τύπος-Άλμπουμ


Αναζήτηση_Άλμπουμ_Τίτλος <--> Βάση_Δεδομένων : Το σύστημα αναζητεί Άλμπουμ με ίδιο τίτλο
Αναζήτηση_Άλμπουμ_Τίτλος --> Αναζήτηση_Τραγουδιών_Άλμπουμ 
Αναζήτηση_Τραγουδιών_Άλμπουμ --> Βάση_Δεδομένων : Για κάθε άλμπουμ, το σύστημα αναζητεί τα 2 δημοφιλέστερα τραγούδια
Αναζήτηση_Τραγουδιών_Άλμπουμ --> Οθόνη_Αναζήτησης : Render


Αναζήτηση_Καλλιτέχνη_Τίτλος <--> Βάση_Δεδομένων : Το σύστημα αναζητεί Καλλιτέχνες με ίδιο τίτλο
Αναζήτηση_Καλλιτέχνη_Τίτλος --> Αναζήτηση_Τραγουδιών_Καλλιτέχνη
Αναζήτηση_Τραγουδιών_Καλλιτέχνη <--> Βάση_Δεδομένων : Για κάθε Καλλιτέχνη, το σύστημα αναζητεί το δημοφιλέστερο τραγούδι
Αναζήτηση_Τραγουδιών_Καλλιτέχνη --> Οθόνη_Αναζήτησης : Render

Αναζήτηση_Τραγουδιών_Τίτλος <--> Βάση_Δεδομένων : Το σύστημα αναζητεί Τραγούδια με ίδιο τίτλο
Αναζήτηση_Τραγουδιών_Τίτλος --> Οθόνη_Αναζήτησης : Render

@enduml