@startuml name

title Supervise Content

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Διαχειριστής
actor Καλλιτέχνης
' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Επιλογών_Άλμπουμ
boundary Μενού_Επιλογών_Τραγουδιού
boundary Αφαίρεση_Popup 
boundary Οθόνη_Εποπτείας_Λογαριασμού_Καλλιτένχη



' =====================================================
' CONTROL OBJECTS
' =====================================================

control Remove_Song
control Remove_Album
control Τράβα_Ιστορικό_Ποινών
control Έκδοση_Απαγόρευσης_Ποινής
control Αφαίρεση_Υλικού
control Απαγόρευση_Καλλιτέχνη
control Προειδοποίηση_Καλλιτέχνη
control Ειδοποίηση_Αλλαγής
' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων

' =====================================================
' USE CASES
' =====================================================

usecase Αναζήτηση_Τραγουδιού_Search_Content
usecase Αναζήτηση_Άλμπουμ_Search_Content

' =====================================================
' INTERACTIONS
' =====================================================
Διαχειριστής --> Αναζήτηση_Τραγουδιού_Search_Content
Αναζήτηση_Τραγουδιού_Search_Content --> Μενού_Επιλογών_Τραγουδιού 
Διαχειριστής --> Μενού_Επιλογών_Τραγουδιού :  επιλέγει το τραγούδι που θέλει και Remove Media
Διαχειριστής --> Αναζήτηση_Άλμπουμ_Search_Content
Αναζήτηση_Άλμπουμ_Search_Content --> Μενού_Επιλογών_Άλμπουμ 
Διαχειριστής --> Μενού_Επιλογών_Άλμπουμ :  επιλέγει το άλμπουμ που θέλει και Remove Media
Μενού_Επιλογών_Τραγουδιού --> Remove_Song
Μενού_Επιλογών_Άλμπουμ --> Remove_Album
Remove_Song --> Αφαίρεση_Popup
Remove_Album --> Αφαίρεση_Popup
Διαχειριστής --> Αφαίρεση_Popup : Εισάγει πληροφορίες για το είδος παραβατικών στοιχείων
Αφαίρεση_Popup --> Τράβα_Ιστορικό_Ποινών
Τράβα_Ιστορικό_Ποινών <--> Βάση_Δεδομένων 
Τράβα_Ιστορικό_Ποινών --> Οθόνη_Εποπτείας_Λογαριασμού_Καλλιτένχη
Διαχειριστής --> Οθόνη_Εποπτείας_Λογαριασμού_Καλλιτένχη
Οθόνη_Εποπτείας_Λογαριασμού_Καλλιτένχη --> Έκδοση_Απαγόρευσης_Ποινής
Έκδοση_Απαγόρευσης_Ποινής --> Αφαίρεση_Υλικού
Αφαίρεση_Υλικού --> Βάση_Δεδομένων
Αφαίρεση_Υλικού --> Απαγόρευση_Καλλιτέχνη : Απαγόρευση
Αφαίρεση_Υλικού --> Προειδοποίηση_Καλλιτέχνη : Προειδοποίηση
Αφαίρεση_Υλικού --> Ειδοποίηση_Αλλαγής : Τίποτα

Απαγόρευση_Καλλιτέχνη --> Βάση_Δεδομένων 
Απαγόρευση_Καλλιτέχνη --> Ειδοποίηση_Αλλαγής

Προειδοποίηση_Καλλιτέχνη --> Βάση_Δεδομένων 
Προειδοποίηση_Καλλιτέχνη --> Ειδοποίηση_Αλλαγής

Ειδοποίηση_Αλλαγής --> Καλλιτέχνης





@enduml