@startuml name

title Upload Song

left to right direction

skinparam shadowing false
skinparam roundcorner 10

' =====================================================
' ACTORS
' =====================================================

actor Καλλιτέχνης

' =====================================================
' BOUNDARY OBJECTS
' =====================================================

boundary Μενού_Πλοήγησης
boundary Πρόγραμμα_Περιήγησης_Αρχείων_Τοπικού_Συστήματος
boundary Οθόνη_Νέου_Τραγουδιού
boundary Same_Name_Popup

' =====================================================
' CONTROL OBJECTS
' =====================================================

control Προσωρινή_Ανάρτηση_Αποθήκευση_Αρχείου
control Επιλογή_Στοιχεία_Πλοήγησης
control Έλεγχος_Για_Ίδιο_Όνομα_Τραγουδιού_Από_Καλλιτέχνη
control Μόνιμη_Ανάρτηση_Αποθήκευση_Αρχείου

' =====================================================
' ENTITY OBJECTS
' =====================================================

entity Βάση_Δεδομένων
entity Τοπικό_Σύστημα_Αρχείων

' =====================================================
' INTERACTIONS
' =====================================================

Καλλιτέχνης --> Μενού_Πλοήγησης : ανέβασμα τραγουδιού
Μενού_Πλοήγησης --> Επιλογή_Στοιχεία_Πλοήγησης
Επιλογή_Στοιχεία_Πλοήγησης --> Πρόγραμμα_Περιήγησης_Αρχείων_Τοπικού_Συστήματος 
Πρόγραμμα_Περιήγησης_Αρχείων_Τοπικού_Συστήματος --> Προσωρινή_Ανάρτηση_Αποθήκευση_Αρχείου
Πρόγραμμα_Περιήγησης_Αρχείων_Τοπικού_Συστήματος <--> Τοπικό_Σύστημα_Αρχείων
Προσωρινή_Ανάρτηση_Αποθήκευση_Αρχείου --> Βάση_Δεδομένων 
Προσωρινή_Ανάρτηση_Αποθήκευση_Αρχείου --> Οθόνη_Νέου_Τραγουδιού
Καλλιτέχνης --> Οθόνη_Νέου_Τραγουδιού : Εισάγει όνομα, εικόνα τραγουδιού
Οθόνη_Νέου_Τραγουδιού --> Έλεγχος_Για_Ίδιο_Όνομα_Τραγουδιού_Από_Καλλιτέχνη
Έλεγχος_Για_Ίδιο_Όνομα_Τραγουδιού_Από_Καλλιτέχνη --> Μόνιμη_Ανάρτηση_Αποθήκευση_Αρχείου : Πρωτότυπο
Μόνιμη_Ανάρτηση_Αποθήκευση_Αρχείου --> Βάση_Δεδομένων

Έλεγχος_Για_Ίδιο_Όνομα_Τραγουδιού_Από_Καλλιτέχνη --> Same_Name_Popup : Υπάρχει ήδη
Same_Name_Popup --> Καλλιτέχνης

@enduml