@startuml Class-Diagram-v0.7

title Spotify-like Desktop App (Clean Architecture - Fixed)

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam shadowing false


' =====================================================
' FRONTEND LAYER (WRAPPER)
' =====================================================

package "Frontend" {

    ' =====================================================
    ' MODEL LAYER
    ' =====================================================

    package "Model Layer" {
        ' -------- ACCOUNT HIERARCHY --------
        abstract class Account {
            - id : String
            - username: String
            - email: String
            - status : AccountStatus
        --
            + getId() : String
            + getUsername() : String
            + getEmail() : String
            + getStatus() : AccountStatus
        }

        class User {
            - displayName: String
            - profilePictureUrl: String
            --
            + getDisplayName() : String
            + setDisplayName(displayName : String) : void
            + getProfilePictureUrl() : String
            + setProfilePictureUrl(profilePictureUrl : String) : void
        }

        class Artist {
            - bio : String
            - followersCount : int
            --
            + getBio() : String
            + setBio(bio : String) : void
            + getFollowersCount() : int
            + setFollowersCount(count : int) : void
        }

        class Admin {
            
        }

        class ArtistRequest{
            - applicantId : int
            - status : ArtistRequestStatus
            - reason : String
            --
            + getUserId() : int
            + getStatus() : ArtistRequestStatus
            + getReason() : String
        }

        User -- ArtistRequest : files
        Admin -- ArtistRequest : inspects

        Account <|-- User
        Account <|-- Artist
        Account <|-- Admin

        interface ILibraryAsset {
            + getTitle() : String
            + getId() : int
        }

        Song ..|> ILibraryAsset
        Album ..|> ILibraryAsset
        Playlist ..|> ILibraryAsset

        ' -------- MUSIC CORE --------
        class Song {
            - artist : Artist 
            - songId : int
            - title : String
            - duration : int
            - filepathUrl : String
            --
            + getTitle() : String
            + getArtist() : Artist
            + getDuration() : int
            + getFilepathUrl() : String
            + getId() : int
            + checkIfEqual(song : Song)
        }

        class Album {
            - artist : Artist
            - albumId : int
            - title : String
            - releaseDate : Date
            - songs : List<Song>
            --
            + getTitle() : String
            + setTitle(title : String) : void
            + getArtist() : Artist
            + getReleaseDate() : Date
            + getId() : int
            + getSongs() : List<Song>
            + addSong(song : Song) : void
            + removeSong(song : Song) : void
        }

        class AlbumItem {
            - song : Song
            - trackNumber : int
            - dateAdded : Date
            --
            + getSong() : Song
            + getTrackNumber() : int
            + void setTrackNumber(trackNumber : int) : void
            + getDateAdded() : Date
        }

        Artist -- Song : creates
        Artist -- Album : creates

        Album -- AlbumItem
        AlbumItem -- Song

        ' -------- PLAYLIST SYSTEM --------
        class Playlist {
            - playlistItems : List<PlaylistItem>
            - creator : User
            - coauthors : List<User>
            --
            + getSongs() : List<Song>
            + addSong(song : Song) : void
            + removeSong(song : Song) : void
            + getTitle() : String
            + setTitle(title : String) : void
            + getCreator() : User
            + getCoauthors() : List<User>
            + addCoauthor(user : User) : void
            + removeCoauthor(user : User) : void
            + toggleVisibility() : void
            + getPlaylistItems() : List<PlaylistItem>
        }

        class PlaylistItem {
            - song : Song
            - position : int
            --
            + getSong() : Song
            + getPosition() : int
            + setPosition(position : int) : void
        }

        User -- Playlist : owns
        Playlist -- PlaylistItem
        PlaylistItem -- Song
        Album -- Playlist

        ' -------- LIBRARY --------
        class Library {
            - assets : List<ILibraryAsset>
            --
            + getAssets() : List<ILibraryAsset>
            + addAsset(asset : ILibraryAsset) : void
            + removeAsset(asset : ILibraryAsset) : void
        }

        User -- Library

        Library -- ILibraryAsset

        ' -------- LISTENING HISTORY --------
        class ListeningHistory { 
            - history : List<ListeningHistoryItem>
            --
            + addSong(Song song) : void
            + getHistory() : List<ListeningHistoryItem>
        }

        class ListeningHistoryItem {
            - song : Song
            - playedAt : LocalDateTime
            --
            + getSong() : Song
            + getPlayedAt() : LocalDateTime
        }

        User --> ListeningHistory
        ListeningHistory -- ListeningHistoryItem
        ListeningHistoryItem -- Song
    }

    ' =====================================================
    ' DTO LAYER
    ' =====================================================

    package "DTO Layer" {
        folder "Requests" {
            class AddSongRequest {

            }

            class ApproveArtistRequest {

            }

            class ArtistApplicationRequest {

            }

            class SongRequest {

            }
        }

        folder "Responses" {
            ' ------ Respones ----- '
            class PlaylistResponse {

            }

            class AddSongResponse {

            }

            class ArtistRequestResponse {

            }

            class ApiResponse {

            }

            class SongResponse {

            }
        }
    }

    ' =====================================================
    ' VIEW LAYER
    ' =====================================================

    package "View" {

        interface View
        interface LibraryAssetView

        ' Persistent UI
        class TopBarView{
            + onHomeClicked() : void
            + onSearchClicked() : void
            + onProfileClicked() : void
        }
       class MusicPlayerView{
            + onPlayClicked() : void
            + onPauseClicked() : void
            + onNextClicked() : void
            + onPreviousClicked() : void
            + onVolumeChanged() : void
            + onShuffleClicked() : void
            + onRepeatClicked() : void

            'WIP'
            + onQueueClicked() : void
        }
        class LibraryView{
            + onAssetClicked(asset : ILibraryAsset) : void
            + onAssetRightClicked(asset : ILibraryAsset) : void
        }

        ' Main screens
        class HomeView
        
        class SearchView {
            + onSearchButtonClicked() : void
        }

        class SongView {
            - songController : SongController
            + onRightClickSong() : void
            - showOptionsMenu() : void
            + onAddToPlaylistClicked() : void
            - showPlaylistSelectionDialog() : void
            + onConfirmAddToPlaylistClicked(playlistId : int, songId : int) : void
            + showExtraMenu() : void
            + showErrorDialog(message : String) : void
            + showSuccessDialog(message : String) : void
        }
        class AlbumView
        class PlaylistView{
            + onSongClicked(song : Song) : void
            + onRemoveSongClicked(song : Song) : void
            + addSong(song : Song) : void
        }
        class ArtistView
        class LoginView

        class UserProfileView{
            + OnSettingsClicked() : void
            + OnLogoutClicked() : void
        }

        class AdminView {
            - adminController : AdminController
            - artistRequests : List<ArtistRequest>
            --
            + setAdminController(adminController : AdminController)
            + setArtistRequests(artistRequests : List<ArtistRequest>)
            + onArtistRequestClicked()
            + displayArtistRequests(artistRequests : List<ArtistRequest>)
            + onArtistRequestShowDetailsClicked(artistRequest : ArtistRequest)
            + showArtistRequestDetails(artistRequest : ArtistRequest)
            + onApproveArtistRequestClicked(int requestId)
            + onRejectArtistRequestClicked(int requestId)
            + showMessage(message : String)
        }

        class ArtistProfileView {
            - artistProfileController : ArtistProfileController
            --
            + setArtistProfileController(controller : ArtistProfileController) : void
            + onUploadSongClicked() : void
            + display() : void
        }

        class UploadSongView {
            - uploadController : UploadController
            --
            + setUploadController(controller : UploadController) : void
            + display() : void
            + onSelectFileClicked() : void
            + onSubmitButtonClicked() : void
            + displaySelectedSongFilepath(filePath : String) : void
            + displaySelectedImageCover(imageFilePath : String) : void
            + displayError(message : String) : void
            + displaySuccess(message : String) : void
        }


        ' Library sub views
        class LibrarySongView
        class LibraryAlbumView
        class LibraryPlaylistView
        class LibraryArtistView

        class PaymentView

        View <|.. HomeView
        View <|.. SearchView
        View <|.. SongView
        View <|.. AlbumView
        View <|.. PlaylistView
        View <|.. ArtistView
        View <|.. LoginView
        View <|.. UserProfileView
        View <|.. AdminView
        View <|.. LibraryView
        View <|.. RightClickMenuView
        View <|.. PaymentView

        LibraryAssetView <|.. LibrarySongView
        LibraryAssetView <|.. LibraryAlbumView
        LibraryAssetView <|.. LibraryPlaylistView
        LibraryAssetView <|.. LibraryArtistView

        LibraryView <|.. LibraryAssetView
    }

    ' =====================================================
    ' CONTROLLER LAYER
    ' =====================================================

    package "ControllerFrontend" as cf{

         interface IController {
            + draw() : void
        }

        class TunixApp {
            - {static} current : IController

            + {static} main(args : String[]) : void
            + {static} initialize() : void

            - {static} drawPersistentElements() : void
            - {static} drawCenter() : void

            + onPlaylistClicked() : void
            + onAlbumClicked() : void
            + onSongClicked() : void
            + onHomeClicked() : void
            + onSearchClicked() : void
            + onProfileClicked() : void
        }

        class MusicPlayerController {
            - main : TunixApp
            - player : MusicPlayer
            + MusicPlayerController(main : TunixApp, player : MusicPlayer)
            + draw() : void
            + onPlayClicked() : void
            + onPauseClicked() : void
            + onNextClicked() : void
            + onPreviousClicked() : void
            + onVolumeChanged() : void
            + onShuffleClicked() : void
            + onRepeatClicked() : void

            'WIP'
            + onQueueClicked() : void
        }

        class HomeController {
            - main : TunixApp
            + HomeController(main : TunixApp)
            + draw() : void
            
        }

        class LibraryController {
            - main : TunixApp
            - library : Library
            + LibraryController(main : TunixApp, library : Library)
            + draw() : void
            - fetchLibraryAssets() : List<ILibraryAsset>
            + getLibraryAssets() : List<ILibraryAsset>
            + onAssetClicked(asset : ILibraryAsset) : void
            + onAssetRightClicked(asset : ILibraryAsset) : void
        }

        class TopBarController {
            - main : TunixApp
            --
            + TopBarController(main : TunixApp)
            + draw() : void
            + onHomeClicked() : void
            + onSearchClicked() : void
            + onProfileClicked() : void
        }

        class PlaylistController {
            - main : TunixApp
            - playlist : Playlist
            + PlaylistController(main : TunixApp, playlist : Playlist)
            + draw() : void
            + onSongClicked(song : Song) : void
            + onRemoveSongClicked(song : Song) : void
            + addSong(song : Song) : void
        }

        class ProfileController {
            - main : TunixApp
            - user : User
            + ProfileController(main : TunixApp, user : User)
            + OnSettingsClicked() : void
            + OnLogoutClicked() : void
            + draw() : void
        }

        class ArtistProfileController {
            - main : TunixApp
            - artist : Artist
            + ArtistProfileController(main : TunixApp, artist : Artist)
            + onUploadSongClicked() : void
            + draw() : void
        }

        class LoginController
        class AdminController{
            - adminView : AdminView
            - adminService : AdminService
            - artistRequestService : ArtistRequestService
            --
            + AdminController(adminView : AdminView, adminService : AdminService, artistRequestService : ArtistRequestService)
            + onArtistRequestClicked() : List<ArtistRequest>
            + showArtistRequestDetails(request : ArtistRequest) : void
            + onApproveRequestClicked(requestId : int) : void
            + onRejectRequestClicked(requestId : int, reason : String) : void
        }
        class UserProfileController
        class ArtistProfileController{
            - artistProfileView : ArtistProfileView
            - artistProfileService : ArtistProfileService
            - EventBus : EventBus
            - artist : Artist
            --
            + ArtistProfileController(artistProfileView : ArtistProfileView, artistProfileService : ArtistProfileService, EventBus : EventBus, artist : Artist)
            + onUploadSongClicked() : void
            + draw() : void        
        }
        class RightClickMenuController
        class SearchController
        
        class SongController {
            - songService : SongService
            - songView : SongView
            - playlistService : PlaylistService
            --
            + addSongToPlaylist(playlistId : int, songId : int) : void
            + showSongAlreadyInPlaylist() : void
            + showErrorDialog(message : String) : void
            + showSuccess(message : String) : void
        }

        class UploadSongController {
            - uploadSongView : UploadSongView
            - songService : SongService
            - eventBus : EventBus
            --
            + UploadSongController(uploadSongView : UploadSongView, songService : SongService, eventBus : EventBus)
            + onSelectFileClicked() : void
            + onSubmitButtonClicked() : void
            + draw() : void
            + displaySelectedFile(filepath : String) : void
            + displaySelectedImageCover(imageFilePath : String) : void
            + displayError(message : String) : void
            + displaySuccess(message : String) : void
            + songUploadSuccess() : void
        }

        class AlbumController

        class PaymentController

        MusicPlayerController ..|> IController
        HomeController ..|> IController
        LibraryController ..|> IController
        TopBarController ..|> IController
        PlaylistController ..|> IController
        ProfileController ..|> IController
        RightClickMenuController ..|> IController
        PaymentController ..|> IController
    }
    
    ' =====================================================
    ' SERVICE LAYER
    ' =====================================================

    package "ServiceFrontend" as sf{

        class ListeningHistoryService {
            + addSong(song : Song) : void
            + addPlaylist(pl : Playlist) : void
            + addAlbum(al : Album) : void
            + getHistory(userId) : List<ILibraryAsset>
        }

        class LibraryService {

            + getLibrary(userId : int) : Library

            + getAssets(userId : int) : List<ILibraryAsset>

            + addAsset(userId : int, assetId : int) : void

            + removeAsset(userId : int, assetId : int) : void
        }

        class PlaybackService {
            - currentSong : Song
            - queue : List<Song>
            - volume : int
            - playing : boolean

            + playSong(song : Song) : void
            + pauseSong() : void
            + resumeSong() : void
            + stopSong() : void

            + nextSong() : void
            + previousSong() : void

            + addToQueue(song : Song) : void
            + removeFromQueue(song : Song) : void
            + clearQueue() : void

            + setVolume(volume : int) : void

            + getCurrentSong() : Song
            + getQueue() : List<Song>

            + isPlaying() : boolean
        }
        class SearchService

        class LoginService {

            - currentUser : User
            - authToken : String

            + login(email : String, password : String) : User
            + register(name : String, email : String, password : String) : User
            + logout() : void

            + isLoggedIn() : boolean
            + getCurrentUser() : User
        }

        class UserService {

            + getUserById(userId : int) : User

            + getUserProfile(userId : int) : User

            + updateUserProfile(user : User) : void

            + deactivateUser(userId : int) : void
        }


        class ArtistRequestService {
            - artistRequestApi : ArtistRequestApi
            --
            + submitRequest(userId : int) : void

            + getRequests() : List<ArtistRequest>

            + approveRequest(requestId : int) : void

            + rejectRequest(requestId : int) : void
        }
        
        class FollowService {

            + followArtist(userId : int, artistId : int) : void

            + unfollowArtist(userId : int, artistId : int) : void

            + getFollowedArtists(userId : int) : List<Artist>

            + isFollowing(userId : int, artistId : int) : boolean
        }

        class PlaylistService {

            + getPlaylist(playlistId : int) : Playlist

            + findByUserId(userId : int) : List<Playlist>

            + getSongsByPlaylistId(playlistId : int) : List<Song>

            + createPlaylist(name : String, creatorId : int) : Playlist

            + deletePlaylist(playlistId : int) : Boolean

            + addSongToPlaylist(playlistId : int, songId : int) : Boolean

            + removeSong(playlistId : int, songId : int) : Boolean

            + addCoauthor(playlistId : int, userId : int) : Boolean

            + removeCoauthor(playlistId : int, userId : int) : Boolean

            + renamePlaylist(playlistId : int, name : String) : Boolean

            + checkIfSongInPlaylist(playlistId: int, songId : int) : boolean
        }

        class SongService {

            + getSongById(songId : int) : Song

            + getSongsByPlaylist(plId : int) : List<Song>

            + uploadSong(song : Song) : Song

            + deleteSong(songId : int) : Boolean

            + checkDuplicateSong() : void
        }

        class AdminService {
            + postIssueWarning() : Boolean
            + postBan() : Boolean
            + postRejectResponse(applicationId : int) : String
            + postApproveResponse(applicationId : int) : String
            + getSongWarnings(songId : int) : List<String>
        }

        class ArtistService {
            + getArtist(searchName : String) : List<Artist>
        }

        class PaymentService
    }

    ' =====================================================
    ' Api LAYER
    ' =====================================================

    package "Api" as api{

        class ApiClient {
            - httpClient : HttpClient
            - baseUrl : String
            - objectMapper : ObjectMapper
            --
            + get(url : String) : ApiResponse
            + post(url : String, body : Object) : ApiResponse
            + put(url : String, body : Object) : ApiResponse
            + delete(url : String) : ApiResponse
        }

        class SongClientApi {
            - apiClient : ApiClient
            --
            + uploadSong(songFormDTO : SongFormDTO) : ApiResponse<SongResponse>
        }

        class PlaylistApi {
            - apiClient : ApiClient
            --
            + addSongToPlaylist(songId : int, playlistId : int) : ApiResponse<AddResponse>
            + postAddSongToPlaylist(songid : int, playlistId : int) : boolean
            + updatePlaylist() : void
        }
        class AlbumApi
        class SongApi
        class LibraryApi
        class UserApi
        class AdminApi
        class LoginApi
        class ArtistApi
        class ArtistRequestApi{
            - ApiClient : ApiClient
            --
            + ArtistRequestApi(apiClient : ApiClient)
            + getAllArtistRequests() : ApiResponse<List<ArtistRequest>>
            + approveRequest(requestId : int) : ApiResponse<ArtistRequestResponse>
            + rejectRequest(requestId : int, reason : String) : ApiResponse<ArtistRequestResponse>
        }
        class PaymentApi
    }

    ' =====================================================
    ' EVENT SYSTEM
    ' =====================================================

    package "EventSystem" {

        interface Event
        class EventBus

        class ShowHomeEvent
        class ShowSearchEvent
        class ShowPlaylistEvent
        class ShowSongEvent
        class ShowAlbumEvent
        class PlaySongEvent
        class LoginEvent

        Event <|-- ShowHomeEvent
        Event <|-- ShowSearchEvent
        Event <|-- ShowPlaylistEvent
        Event <|-- ShowSongEvent
        Event <|-- ShowAlbumEvent
        Event <|-- PlaySongEvent
        Event <|-- LoginEvent
    }

    ' =====================================================
    ' APP BOOTSTRAP
    ' =====================================================

        MusicApp -- TopBarController
        MusicApp -- LibraryController
        MusicApp -- MusicPlayerController
        MusicApp -- HomeView

    ' =====================================================
    ' VIEW → CONTROLLER
    ' =====================================================

        HomeView -- HomeController
        SearchView -- SearchController
        SongView -- SongController
        AlbumView -- AlbumController
        PlaylistView -- PlaylistController
        ArtistView -- ArtistProfileController
        LoginView -- LoginController
        LibraryView -- LibraryController
        TopBarView -- TopBarController
        MusicPlayerView -- MusicPlayerController
        UserProfileView -- UserProfileController
        AdminView -- AdminController
        UploadSongView -- UploadSongController
        ArtistProfileView -- ArtistProfileController
        PaymentView -- PaymentController


    ' =====================================================
    ' CONTROLLER → SERVICE
    ' =====================================================
        SearchController -- SearchService
        LoginController -- LoginService
        LibraryController -- LibraryService
        MusicPlayerController -- PlaybackService
        UserProfileController -- UserService
        AdminController -- AdminService
        UserProfileController -- ArtistRequestService

        ArtistProfileController -- FollowService
        ArtistProfileController -- ArtistService

        PlaylistController -- PlaylistService
        LibraryController -- PlaylistService

        SongController -- SongService

        UploadSongController -- SongService

        PaymentController -- PaymentService


    ' =====================================================
    ' CONTROLLER → EVENTBUS
    ' =====================================================
        HomeController -- EventBus
    ' =====================================================
    ' SERVICE → Api
    ' =====================================================

        LibraryService -- LibraryApi
        LibraryService -- UserApi

        SearchService -- SongClientApi
        SearchService -- AlbumApi
        SearchService -- PlaylistApi

        PlaybackService -- SongApi
        PlaybackService -- PlaylistApi

        LoginService -- UserApi
        UserService -- UserApi

        AdminService -- AdminApi

        PlaylistApi -- PlaylistService

        FollowService -- UserApi

        LoginService -- LoginApi

        ArtistService -- ArtistApi

        ArtistRequestService -- ArtistRequestApi

        SongService -- SongClientApi

        PaymentService -- BankApi
        PaymentService -- PaymentApi

    ' =====================================================
    ' Api → CLIENT
    ' =====================================================

        SongApi -- ApiClient
        PlaylistApi -- ApiClient
        AlbumApi -- ApiClient
        LibraryApi -- ApiClient
        UserApi -- ApiClient
        ArtistApi -- ApiClient
        LoginApi -- ApiClient
        ArtistRequestApi -- ApiClient
        AdminApi -- ApiClient
        PaymentApi -- ApiClient

    

    ' =====================================================
    ' EVENT SYSTEM USAGE
    ' =====================================================

        HomeController ..> EventBus : publish
        SearchController ..> EventBus : publish
        PlaylistController ..> EventBus : publish
        SongController ..> EventBus : publish
        AlbumController ..> EventBus : publish
        LibraryController ..> EventBus : publish
        LoginController ..> EventBus : publish

        MusicPlayerController ..> EventBus : subscribe

    ' =====================================================
    ' MODEL USAGE (MINIMAL)
    ' =====================================================

        LibraryService -- Library
        LibraryService -- LibraryAsset
        PlaybackService -- Song
        LoginService -- Account
        UserService -- Account

}
 
left to right direction
package "Spring Backend" <<External System>> {

' =====================================================
' DOMAIN LAYER (ENTITIES)
' =====================================================

package "Domain (Entities)" as EB {

    class Account
    class User
    class Artist
    class Admin
    class Song
    class Album
    class Playlist
    class Library

    Account <|-- User
    Account <|-- Artist
    Account <|-- Admin

    Playlist -- Song
    Album -- Song
    Library -- Song
    Library -- Playlist
    Library -- Album
    User -- Library
}

' =====================================================
' DTO LAYER
' =====================================================

package "DTO Layer" {

    class SongDTO
    class AlbumDTO
    class PlaylistDTO
    class UserDTO
    class ArtistDTO
    class LibraryDTO
}

' =====================================================
' CONTROLLER LAYER (REST Api)
' =====================================================

package "Backend Controller Layer (REST)" as C{

    interface Api

    class UserBackendController
    class ArtistBackendController
    class AdminBackendController
    class SongBackendController
    class AlbumBackendController
    class PlaylistBackendController {
        + addSongToPlaylist(playlistId : int, songId : int) : boolean
    }
    class LibraryBackendController
    class ListeningHistoryBackendController
    class ArtistRequestBackendController
    class PaymentBackendController

    Api <|.. UserBackendController
    Api <|.. ArtistBackendController
    Api <|.. AdminBackendController
    Api <|.. SongBackendController
    Api <|.. AlbumBackendController
    Api <|.. PlaylistBackendController
    Api <|.. LibraryBackendController
    Api <|.. ListeningHistoryBackendController
    Api <|.. ArtistRequestBackendController
    Api <|.. PaymentBackendController
}

' =====================================================
' SERVICE LAYER
' =====================================================

package "BackendService Layer" as S{

    interface BackendService

    class UserBackendService
    class ArtistBackendService
    class AdminBackendService
    class SongBackendService
    class AlbumBackendService
    class PlaylistBackendService {
        addSongToPlaylist(playlistId : int, songId : int) : boolean
        checkDuplicateSong(playlistId : int, songId : int) : boolean
    }
    class LibraryBackendService
    class ListeningHistoryBackendService
    class ArtistRequestBackendService
    class PaymentBackendService

    BackendService <|.. UserBackendService
    BackendService <|.. ArtistBackendService
    BackendService <|.. AdminBackendService
    BackendService <|.. SongBackendService
    BackendService <|.. AlbumBackendService
    BackendService <|.. PlaylistBackendService
    BackendService <|.. LibraryBackendService
    BackendService <|.. ListeningHistoryBackendService
    BackendService <|.. ArtistRequestBackendService
    BackendService <|.. PaymentBackendService
}

' =====================================================
' BackendRepository LAYER
' =====================================================

package "BackendRepository Layer (JPA)" {

    interface JpaBackendRepository

    class UserBackendRepository
    class ArtistBackendRepository
    class AdminBackendRepository
    class SongBackendRepository
    class AlbumBackendRepository
    class PlaylistBackendRepository {
       + addSongQuery() : boolean
       + findByPlaylistIdAndSongId(playlistId : int, songId : int) : boolean
    }

    class LibraryBackendRepository
    class ListeningHistoryBackendRepository
    class ArtistRequestBackendRepository
    class PaymentRepository

    JpaBackendRepository <|.. UserBackendRepository
    JpaBackendRepository <|.. ArtistBackendRepository
    JpaBackendRepository <|.. AdminBackendRepository
    JpaBackendRepository <|.. SongBackendRepository
    JpaBackendRepository <|.. AlbumBackendRepository
    JpaBackendRepository <|.. PlaylistBackendRepository
    JpaBackendRepository <|.. LibraryBackendRepository
    JpaBackendRepository <|.. ListeningHistoryBackendRepository
    JpaBackendRepository <|.. ArtistRequestBackendRepository
    JpaBackendRepository <|.. PaymentRepository
}

' =====================================================
' FLOW: API → CONTROLLER
' =====================================================
ApiClient -- Api

' =====================================================
' FLOW: CONTROLLER → BackendService
' =====================================================

SongBackendController -- S.SongBackendService
PlaylistBackendController -- S.PlaylistBackendService
AlbumBackendController -- S.AlbumBackendService
UserBackendController -- S.UserBackendService
ArtistBackendController -- S.ArtistBackendService
LibraryBackendController -- S.LibraryBackendService
PaymentBackendController -- S.PaymentBackendService

' =====================================================
' FLOW: BackendService → BackendRepository
' =====================================================

S.SongBackendService -- SongBackendRepository
S.PlaylistBackendService -- PlaylistBackendRepository
S.AlbumBackendService -- AlbumBackendRepository
S.UserBackendService -- UserBackendRepository
S.ArtistBackendService -- ArtistBackendRepository
S.LibraryBackendService -- LibraryRepository
S.PaymentBackendService -- PaymentRepository

' =====================================================
' BackendService → DOMAIN
' =====================================================

S.SongBackendService .. E.Song
S.PlaylistBackendService .. E.Playlist
S.AlbumBackendService .. E.Album
S.UserBackendService .. E.User
S.LibraryBackendService .. E.Library
S.ArtistBackendService .. E.Artist
S.PaymentBackendService .. E.User

' =====================================================
' CONTROLLER → DTO
' =====================================================

SongBackendController -- SongDTO
PlaylistBackendController -- PlaylistDTO
AlbumBackendController -- AlbumDTO
UserBackendController -- UserDTO
ArtistBackendController -- ArtistDTO
LibraryBackendController -- LibraryDTO

}
@enduml